In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.8.0.dev20250316+cu128


### Creating Tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

To create tensor use torch.tensor

In [16]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [17]:
vector.ndim

1

In [ ]:
# In square bracket
vector.shape

torch.Size([2])

In [25]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [21]:
MATRIX.ndim

2

In [22]:
MATRIX[1]

tensor([ 9, 10])

In [23]:
MATRIX.shape

torch.Size([2, 2])

In [26]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [27]:
TENSOR.ndim

3

In [28]:
TENSOR.shape

torch.Size([1, 3, 3])

In [29]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors
Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [36]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor


tensor([[0.9016, 0.5501, 0.2276, 0.0092],
        [0.6444, 0.0357, 0.2328, 0.7750],
        [0.4658, 0.9441, 0.9097, 0.5306]])

In [39]:
random_tensor.ndim

2

In [38]:
random_tensor.shape

torch.Size([3, 4])

In [37]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [41]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [43]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [44]:
ones.dtype

torch.float32

In [45]:
random_tensor.dtype

torch.float32

### Creating a range of tensor and tensors-like

In [ ]:
# Use torch.range() and get deprecated message, use torch.arrange() remove in future 
one_to_ten = torch.arange(start=1 , end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Creating tensors like mean the same shape
ten_zeros = torch.zeros_like(input=one_to_ten) 
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not ont the right device

In [66]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, # What datatype is the tensor (e.g. float32 or float16) 
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whethever or not to track gradients

In [60]:
float_32_tensor.dtype

torch.float16

In [67]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [69]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])