In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

c:\Users\mydea\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\_pytree.py:173: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(


2.8.0.dev20250316+cu128


### Creating Tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

To create tensor use torch.tensor

In [16]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [17]:
vector.ndim

1

In [ ]:
# In square bracket
vector.shape

torch.Size([2])

In [25]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [21]:
MATRIX.ndim

2

In [22]:
MATRIX[1]

tensor([ 9, 10])

In [23]:
MATRIX.shape

torch.Size([2, 2])

In [26]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [27]:
TENSOR.ndim

3

In [28]:
TENSOR.shape

torch.Size([1, 3, 3])

In [29]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors
Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [36]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor


tensor([[0.9016, 0.5501, 0.2276, 0.0092],
        [0.6444, 0.0357, 0.2328, 0.7750],
        [0.4658, 0.9441, 0.9097, 0.5306]])

In [39]:
random_tensor.ndim

2

In [38]:
random_tensor.shape

torch.Size([3, 4])

In [37]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [41]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [43]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [44]:
ones.dtype

torch.float32

In [45]:
random_tensor.dtype

torch.float32

### Creating a range of tensor and tensors-like

In [ ]:
# Use torch.range() and get deprecated message, use torch.arrange() remove in future 
one_to_ten = torch.arange(start=1 , end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Creating tensors like mean the same shape
ten_zeros = torch.zeros_like(input=one_to_ten) 
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not ont the right device

In [9]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, # What datatype is the tensor (e.g. float32 or float16) 
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whethever or not to track gradients

In [10]:
float_32_tensor.dtype

torch.float32

In [12]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [13]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [16]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [17]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shapea from a tensor, can uise tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [18]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2970, 0.5505, 0.8439, 0.2261],
        [0.1091, 0.6340, 0.0404, 0.6317],
        [0.9388, 0.3042, 0.7848, 0.8418]])

In [22]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2970, 0.5505, 0.8439, 0.2261],
        [0.1091, 0.6340, 0.0404, 0.6317],
        [0.9388, 0.3042, 0.7848, 0.8418]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations in include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [25]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [26]:
# Multiply a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [27]:
# Subtraction 10
tensor - 10

tensor([-9, -8, -7])

In [28]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [29]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [30]:
torch.subtract(tensor, 10)

tensor([-9, -8, -7])


### Matrix multiplication

Two main wasys of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work
* **Note:** @ mean dot product
2. The resulting matrix has the shape of the **outer dimensions** :
* (2, 3) @ (3, 2) -> (2, 2)

In [32]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [33]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [34]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 2 ms


In [35]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 1 ms


tensor(14)

In [36]:
%%time
tensor @ tensor

CPU times: total: 0 ns
Wall time: 1.01 ms


tensor(14)

### One of the most common errors in deep learning: shape errors

In [39]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul